site_name: Gradewing Guide
#site_url: http://127.0.0.1:8000/docs123

theme:
  favicon: assets/images/gradewing_icon.png
  logo: assets/images/gradewing_icon_white.png
  name: material
  font:
    text: Nunito
  palette:
    primary: teal
    accent: indigo
  features:
    - navigation.instant
    - navigation.tabs # Top-level categories
    - navigation.sections # Sidebar organization
    - search.suggest
    - content.code.copy

nav:
  - Gradewing: index.md
  - Data Manager's Guide:
      - Getting Started: data-manager/getting-started.md
      - The Operational Roadmap: data-manager/operational-roadmap.md
      - Set up:
          - Overview: data-manager/setup.md
          - The Student Setup: data-manager/student-setup.md
      - Gradebooks & Reports: data-manager/gradebook.md
      
  - Teacher's Guide:
      - Getting Started: teacher/getting-started.md
      - Gradebooks & Reports: teacher/gradebook.md
      - Student & Learner Records: teacher/record.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.mermaid_format
  - attr_list
  - pymdownx.blocks.caption

extra_javascript:
  - https://unpkg.com