site_name: Gradewing Guide
site_url: https://pablopenlop.github.io/gradewing_guide/

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      zoomable: true
      draggable: true

theme:
  favicon: assets/images/gradewing_icon.png
  logo: assets/images/gradewing_icon_white.png
  name: material
  font:
    text: Nunito
  palette:
    primary: teal
    accent: indigo
  features:
    - navigation.instant
    #- navigation.tabs # Top-level categories
    - navigation.sections # Sidebar organization
    - search.suggest
    - content.code.copy

nav:
  - Gradewing: index.md
  - Data Manager's Guide:
      - Getting Started: data-manager/getting-started.md
      - Setup: data-manager/setup.md
      - User accounts: data-manager/users.md
      - Student Setup: data-manager/student-setup-v2.md
      - Grading: data-manager/grading.md
      # - Reporting: data-manager/reporting.md
      
  - Internal docs:
      - Technical guide: other.md
      - Deployment: internal/deployment.md
      - Stripe: stripedoc.md
  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.blocks.caption
  - toc:
      toc_depth: 3



